/**
 * FileServer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIUploadFile200Response.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIUploadFile200Response::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Filename.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("filename")); WriteJsonValue(Writer, Filename.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIUploadFile200Response::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("filename"), Filename);

	return ParseSuccess;
}

}
