version: "3.9"
services:
  app:
    build:
      context: ../
      dockerfile: ExampleServerDockerfile
    volumes:
      - saved:/usr/app/server/saved
    ports:
      - "3000:3000"
  maintenance:
    image: debian:bullseye-slim
    volumes:
      - saved:/usr/app/server/saved
      - ./:/usr/maintenance
    working_dir: /usr/maintenance
volumes:
  saved:
    driver: local