/**
 * FileServer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIDefaultApi.h"

#include "OpenAPIHelloOperation200Response.h"
#include "OpenAPIUploadFile200Response.h"
#include "OpenAPIUploadFileRequest.h"

namespace OpenAPI
{

/* 

*/
class OPENAPI_API OpenAPIDefaultApi::HelloOperationRequest : public Request
{
public:
    virtual ~HelloOperationRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

};

class OPENAPI_API OpenAPIDefaultApi::HelloOperationResponse : public Response
{
public:
    virtual ~HelloOperationResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIHelloOperation200Response Content;
};

/* Upload file

*/
class OPENAPI_API OpenAPIDefaultApi::UploadFileRequest : public Request
{
public:
    virtual ~UploadFileRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* Upload file to server */
	OpenAPIUploadFileRequest OpenAPIUploadFileRequest;
};

class OPENAPI_API OpenAPIDefaultApi::UploadFileResponse : public Response
{
public:
    virtual ~UploadFileResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIUploadFile200Response Content;
};

}
